project:
  type: website

website:
  title: "Seoyeon's Portfolio"
  
  page-footer:
    border: true
    
  navbar:
    left:
      - text: Main_Blog
        href: https://seoyeonc.github.io/sy_hub/
      - text: Linkedin
        href: https://www.linkedin.com/in/seoyeon-choi-6b3b60231/
        
    right:
      - about.qmd
      - icon: github
        href: https://github.com/seoyeonc
        
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "**Statistics**"
        contents:
          - 2_rand.qmd
          - 2_pkpd.qmd
          - 2_rwdrwe.qmd
          - 2_pro.qmd
          - 2_kno.qmd
      
format:
  html:
    theme: 
        light: cosmo
    css: styles.css
    toc: true
    code-fold: false
    code-line-numbers: false
    code-copy: false




