---
title: "SEOYEON CHOI"
listing:
  contents: posts
  sort: "date desc"
  type: table
  categories: true
  sort-ui: false
  filter-ui: false
page-layout: full
title-block-banner: true
---

::: {.panel-tabset} 

## Professional Experience

- (10/2022 - 5/2025) Nanum Space Corp.
    - Data Analystic Team / Statistician
- (10/2020 - 9/2022) Jeonbuk National University Hospital Center for Clinical Pharmacology
    - Clinical Statistics Team / Statistician

## Education

- (9/2021 - 8/2023) Jeonbuk National University, South Korea
    - Department of Statistics / Master's degree
    - Supervisor: Guebin Choi
    - Thesis Title: Spectral Analysis of non-Euclidean Data: A New Statistical Methodology for Graph Signal Processing and Graph Neural Network
- (3/2014 - 2/2018) Jeonbuk National University, South Korea
    - Department of Statistics / Bachelor's degree

## Publications

- Choi, S. & Choi, G.(2025). Gode: graph Fourier transform based outlier detection using empirical Bayesian thresholding;
    - Journal of the Korean Statistical Society, 1-21
    - keywords: Outlier Detection, Non-Euclidean Data, Graph Fourier Transform, Bayesian Modelings
    - https://link.springer.com/article/10.1007/s42952-024-00303-1
    
- Choi, S., Sim, J. & Choi, G.(2025) Synthetic Text as Data: On Usefulness and Limitations. 
    - Applied Sciences, 15(10), 5460.
    - keywords: GPT-generated text, synthetic data, data augmentation, MBTI classification, class imbalance, few-shot learning, fine-grained classification, data granularity, large language models
    - https://www.mdpi.com/2076-3417/15/10/5460
    
- Choi, S., Kim, H. & Choi, G.(2026) Cascading Class Activation Mapping: A Counterfactual Reasoning-Based Explainable Method for Comprehensive Feature Discovery
    - CMES-Computer Modeling in Engineering & Sciences, 146(2), 37. (SCIE; 22.4%; Q1)
    - keywords: Explainable AI; Class Activation Mapping; Counterfactual Reasoning; Shortcut Learning; Feature Discovery
    - https://www.techscience.com/CMES/v146n2/66329
    
:::